### ISSUE TITLE
Only watch the slides folder

### ISSUE THREAD

**Issue by alexjbest** [0art0/lean-slides#10]
I think it would be helpful to only watch the folder `slides/`, instead of the entire project with `browser-sync`, to reduce the amount that browser-sync is tracking (in a project I'm working on browser-sync has some issues with some c files in the `.lake` folder for one).

I have this working locally but it's a bit hacky (the folder is set to `slides` in the lakefile, and `slidesUrl` is set to `(← getServerUrl) ++ "/" ++ slidesPath.fileName.get!`), so a nicer implementation would be good.

**Comment by 0art0** [comment]
I think `(← getServerUrl) ++ s!"/{name}.html" would also work here, which is perhaps slightly less hacky (but still needs the modification to the `lakefile`).

**Comment by 0art0** [comment]
I have opened a PR #11 for this. The only downside is that `slidesDir` is defined twice, once in the `lakefile` and again in the main file, but if that seems fine, I can merge this into `main`.

**Comment by alexjbest** [comment]
Yeah that sounds fine to me, and the PR looks good! And would be very helpful avoiding the issues I'm running into above

**Comment by 0art0** [comment]
Merged!

**Comment by alexjbest** [comment]
Thanks!
