### ISSUE TITLE
Script for running the server

### ISSUE THREAD

**Issue by 0art0** [0art0/lean-slides#4]
The current set-up requires users to manually run `browser-sync` with the prescribed set of flags each time. Bundling this into a script (for example, by modifying the code in `LaunchServer.lean`) would make it easier to launch the server. The script should ideally be callable from downstream dependencies as well.

**Comment by PatrickMassot** [comment]
Isn't this fixed since 18e2fcc1e31182decb36bf1227ceb2e9d3839630?

**Comment by 0art0** [comment]
Yes, my bad, I forgot to update this issue afterwards.
